# Generated by Django 4.2.6 on 2024-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
