# Generated by Django 4.2.6 on 2023-12-06 12:32

from django.db import migrations

from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Обзоры',
        'Скидки',
        'Новинки',
        'Партнерам',
        'Специальные предложения'
    ]
    for category in categories:
        BlogCategory.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_tags'),
    ]

    operations = [
        migrations.RunPython(add_blog_categories)
    ]
