# Generated by Django 4.2.6 on 2023-12-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_images_productimages_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
